name: Keep Supabase Alive

on:
  schedule:
    - cron: "*/30 * * * *" # corre de 15 em 15 minutos
  workflow_dispatch: # allows manual run from GitHub

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API
        run: curl -s https://escuteiros-material.vercel.app/api/ping
